In [1]:
import pandas as pd 
import numpy as np 


from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline


import scipy.stats as st
import sklearn.metrics as sm

In [2]:
data = pd.read_csv('weather.csv')
data

,Play,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
0,no,21-12-2013,74.0,60.0,45.0,67,49,43,93,75,...,29.68,29.59,10,7,2,20,4,31,0.46,"Rain , Thunderstorm"
1,yes,22-12-2013,56.0,48.0,39.0,43,36,28,93,68,...,30.13,29.87,10,10,5,16,6,25,0,NaN
2,NaN,23-12-2013,58.0,45.0,32.0,31,27,23,76,52,...,30.49,30.41,10,10,10,8,3,12,0,NaN
3,NaN,24-12-2013,61.0,46.0,31.0,36,28,21,89,56,...,30.45,30.3,10,10,7,12,4,20,0,NaN
4,NaN,25-12-2013,58.0,50.0,41.0,44,40,36,86,71,...,30.33,30.27,10,10,7,10,2,16,T,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1327,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN